%% This function is used to calculate the forward kinematics of a 4 DOF planar manipulator
function [xe, ye] = FK(linkLen, ang1, ang2, ang3, ang4)

xe = linkLen(1)*cos(ang1) +...
     linkLen(2)*cos(ang1 + ang2) +...
     linkLen(3)*cos(ang1 + ang2 + ang3) +...
     linkLen(4)*cos(ang1 + ang2 + ang3 + ang4);
ye = linkLen(1)*sin(ang1) +...
     linkLen(2)*sin(ang1 + ang2) +...
     linkLen(3)*sin(ang1 + ang2 + ang3) +...
     linkLen(4)*sin(ang1 + ang2 + ang3 + ang4);
        
end